### login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}


### view profile
GET {{host}}/api/profile


### update profile
PUT {{host}}/api/profile
Content-Type: application/json

{
  "version": 1,
  "firstName": "test",
  "lastName": "testi",
  "profilePicture": "fdd47618-96ea-4366-ae44-9435e7caa392",
  "oldPassword": null,
  "newPassword": null,
  "newPasswordConfirmation" : null
}
