### login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "AdminP@33"
}

### create ticket
POST {{host}}/api/product/2/ticket
Content-Type: application/json

{
  "title": "ticket-5",
  "type": "BUG",
  "description": "this is a bug"
}

### view ticket
GET {{host}}/api/product/2/ticket/6

### list tickets
GET {{host}}/api/ticket?page=0

### list admin tickets
GET {{host}}/api/product/1/ticket?page=0

### update ticket
PUT {{host}}/api/product/2/ticket/3
Content-Type: application/json

{
  "status": "PENDING"
}
