  name: CI Build
  on:
    push:
      branches:
        - '**'
  jobs:
    build:
      name: Maven Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Java 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
            cache: 'maven'
        - name: Setup Testcontainers Cloud Client
          uses: atomicjar/testcontainers-cloud-setup-action@v1
          with:
            token: ${{ secrets.TC_CLOUD_TOKEN }}
        - name: Build with Maven
          run: ./mvnw verify
        - name: Build and push Docker images
          uses: docker/build-push-action@v5.1.0
          with:
            tags: ticketmastergang/ticketmaster:backend
            
    
