### login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "AdminP@33"
}

### create prduct
POST {{host}}/api/product
Content-Type: application/json

{
  "name": "test2"
}

### view product
GET {{host}}/api/product/2

### update prduct
PUT {{host}}/api/product/2
Content-Type: application/json

{
  "version": 1,
  "description": "Hello"
}

### delete product
DELETE {{host}}/api/product/1
